### ISSUE TITLE
Update doesn't work on MacOS [Twilio CLI]

### ISSUE THREAD

**Issue by onuzbee** [oclif/plugin-update#298] opened 2021-09-17 12:19 UTC
Update plugin doesn't seem to work on MacOS (Fails silently) using `.pkg` installer of oclif-dev pack:macos. 
Could someone help with any possible resolution? 

![Screenshot 2021-09-17 at 5 44 30 PM](https://user-images.githubusercontent.com/16326222/133781138-1078a1df-7a41-4afc-bced-5dc1f7e4ce75.png)

[Twilio-cli Github](https://github.com/twilio/twilio-cli/)

**Comment by onuzbee** [comment] 2021-09-17 13:04
In case Debug logs help: 
 `DEBUG=* twilio update`
```
❯ DEBUG=* twilio update
TWILIO_BINPATH=/usr/local/lib/twilio-cli/bin/twilio /usr/local/lib/twilio-cli/bin/node /usr/local/lib/twilio-cli/bin/run update
  @oclif/config reading core plugin /usr/local/lib/twilio-cli +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/package.json +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/oclif.manifest.json +3ms
  @oclif/config:twilio-cli using manifest from /usr/local/lib/twilio-cli/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /Users/abadhwar/.twilio-cli/package.json +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/package.json +2ms
  @oclif/config loading plugins [
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-help',
  '@oclif/plugin-plugins',
  '@oclif/plugin-warn-if-update-available',
  '@oclif/plugin-update'
] +0ms
  @oclif/config reading core plugin /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-autocomplete +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-autocomplete/package.json +3ms
  @oclif/config reading core plugin /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-help/package.json +0ms
  @oclif/config reading core plugin /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-plugins +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-plugins/package.json +1ms
  @oclif/config reading core plugin /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-warn-if-update-available +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-warn-if-update-available/package.json +0ms
  @oclif/config reading core plugin /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-update +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-update/package.json +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +1ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-update/oclif.manifest.json +1ms
  @oclif/config loadJSON /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-plugins using manifest from /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-warn-if-update-available using manifest from /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-update using manifest from /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-update/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-autocomplete using manifest from /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  @oclif/config config done +8ms
  @oclif/config start init hook +1ms
  twilio:twilio-cli:hooks:init start /usr/local/lib/twilio-cli/src/hooks/init/twilio-api +0ms
  twilio:twilio-cli:hooks:init start /usr/local/lib/twilio-cli/src/hooks/init/buy-phone-number +147ms
  twilio:twilio-cli:hooks:init start /usr/local/lib/twilio-cli/src/hooks/init/plugin-verification +2ms
  twilio:@oclif/plugin-warn-if-update-available:hooks:init start /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update +0ms
  twilio:@oclif/plugin-update:hooks:init start /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-update/lib/hooks/init +0ms
  twilio:twilio-cli:hooks:init done +45ms
  twilio:twilio-cli:hooks:init done +0ms
  twilio:twilio-cli:hooks:init done +1ms
  twilio:@oclif/plugin-update:hooks:init done +22ms
  update-check Error: ENOENT: no such file or directory, stat '/Users/abadhwar/.twilio-cli/version' +0ms
  update-check spawning version refresh +0ms
  twilio:@oclif/plugin-warn-if-update-available:hooks:init done +48ms
  @oclif/config init hook done +201ms
  twilio init version: @oclif/command@1.8.0 argv: [ 'update' ] +0ms
  @oclif/config runCommand update [] +4ms
  @oclif/config:@oclif/plugin-update require /usr/local/lib/twilio-cli/node_modules/@oclif/plugin-update/lib/commands/update.js +207ms
  @oclif/config start prerun hook +24ms
  @oclif/config prerun hook done +0ms
  twilio:update init version: @oclif/command@1.8.0 argv: [] +0ms
  @oclif/config start preupdate hook +2ms
  @oclif/config preupdate hook done +1ms
  http → GET https://twilio-cli-prod.s3.amazonaws.com/channels/stable/twilio-darwin-x64-buildmanifest
  http   user-agent: 'twilio-cli/2.28.0 darwin-x64 node-v14.17.0' +0ms
  http ← GET https://twilio-cli-prod.s3.amazonaws.com/channels/stable/twilio-darwin-x64-buildmanifest 403
  http   connection: 'close'
  http   content-type: 'application/xml'
  http   date: 'Fri, 17 Sep 2021 12:37:01 GMT'
  http   server: 'AmazonS3'
  http   transfer-encoding: 'chunked'
  http   x-amz-id-2: 'CQWXJJwIaFxenYGs8PGDUL+Bodosy5Eb2qbML85yy8m4yBkVFabRt3RCwpw/GQpOljSnNrTLh9I='
  http   x-amz-request-id: 'TC6W573DARAG1ZMG'
  http '<?xml version="1.0" encoding="UTF-8"?>\n' +
  http   '<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>TC6W573DARAG1ZMG</RequestId><HostId>CQWXJJwIaFxenYGs8PGDUL+Bodosy5Eb2qbML85yy8m4yBkVFabRt3RCwpw/GQpOljSnNrTLh9I=</HostId></Error>' +2s
  twilio:update HTTP Error 403 for GET https://twilio-cli-prod.s3.amazonaws.com/channels/stable/twilio-darwin-x64-buildmanifest
  twilio:update <?xml version="1.0" encoding="UTF-8"?>
  twilio:update <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>TC6W573DARAG1ZMG</RequestId><HostId>CQWXJJwIaFxenYGs8PGDUL+Bodosy5Eb2qbML85yy8m4yBkVFabRt3RCwpw/GQpOljSnNrTLh9I=</HostId></Error> +2s
  http → GET https://twilio-cli-prod.s3.amazonaws.com/darwin-x64
  http   user-agent: 'twilio-cli/2.28.0 darwin-x64 node-v14.17.0' +3ms
  http ← GET https://twilio-cli-prod.s3.amazonaws.com/darwin-x64 200
  http   accept-ranges: 'bytes'
  http   cache-control: 'max-age=86400'
  http   connection: 'close'
  http   content-length: '331'
  http   content-type: 'application/json'
  http   date: 'Fri, 17 Sep 2021 12:37:03 GMT'
  http   etag: '"9f46ef47eb920cfde32c5ab378d0dbc3"'
  http   last-modified: 'Fri, 17 Sep 2021 11:27:14 GMT'
  http   server: 'AmazonS3'
  http   x-amz-id-2: '5lKJ34KQonEsuxbSq1cdiSul1Zy84WEfHbqyr1xErRvP0pgB3NN83SyxT28sM0qw3z567iKHUlA='
  http   x-amz-request-id: 'C7H4CXGX8J1AW2JW'
  http   x-amz-version-id: 'm34T2Rsl8F358DkdfEYZzMHrvF1HR0jY'
  http {
  http   version: '2.29.2',
  http   channel: 'stable',
  http   baseDir: 'twilio',
  http   gz: 'https://twilio-cli-prod.s3.amazonaws.com/twilio-v2.29.2/twilio-v2.29.2-darwin-x64.tar.gz',
  http   sha256gz: 'd512354bd6846b95d0b31025c64c96068ea3f18f3b9550274e2355f912d0ee28',
  http   node: { compatible: '>=10.12.0', recommended: '14.17.6' }
  http } +1s
  twilio:update Error: ENOENT: no such file or directory, open '/Users/abadhwar/.twilio-cli/client/bin/twilio' +1s
  http → GET https://twilio-cli-prod.s3.amazonaws.com/twilio-v2.29.2/twilio-v2.29.2-darwin-x64.tar.gz
  http   user-agent: 'twilio-cli/2.28.0 darwin-x64 node-v14.17.0' +3ms
  http ← GET https://twilio-cli-prod.s3.amazonaws.com/twilio-v2.29.2/twilio-v2.29.2-darwin-x64.tar.gz 200
  http   accept-ranges: 'bytes'
  http   cache-control: 'max-age=604800'
  http   connection: 'close'
  http   content-length: '48701440'
  http   content-type: 'application/gzip'
  http   date: 'Fri, 17 Sep 2021 12:37:04 GMT'
  http   etag: '"5e8a64d064c0219fcdcbcdf1debae681-10"'
  http   last-modified: 'Fri, 17 Sep 2021 11:25:54 GMT'
  http   server: 'AmazonS3'
  http   x-amz-id-2: 'lWVFCcahu4EqNnoar0arpRflqF7K/nVV8ZW0yQLMncX8bo905VU1og7QckeiBOIbhqbpGhJ3pHA='
  http   x-amz-request-id: 'K44ZRFVWQ03MWAKQ'
  http   x-amz-version-id: 'p6.UeAtXMpS.JJ9oskRvyfinlKa63oxB' +1s
  oclif-update extracting to /Users/abadhwar/.twilio-cli/client/2.29.2.partial.11828 +0ms
  oclif-update moving /Users/abadhwar/.twilio-cli/client/2.29.2.partial.11828/twilio to /Users/abadhwar/.twilio-cli/client/2.29.2 +16s
  oclif-update done extracting +2ms
  twilio:update touching client at /Users/abadhwar/.twilio-cli/client/2.28.0 +17s
twilio-cli: Updating CLI from 2.28.0 to 2.29.2... done
  twilio:update restarting CLI after update /Users/abadhwar/.twilio-cli/client/bin/twilio +1ms
TWILIO_BINPATH=/Users/abadhwar/.twilio-cli/client/bin/twilio /Users/abadhwar/.twilio-cli/client/2.29.2/bin/node /Users/abadhwar/.twilio-cli/client/2.29.2/bin/run update
  @oclif/config reading core plugin /Users/abadhwar/.twilio-cli/client/2.29.2 +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/package.json +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/oclif.manifest.json +3ms
  @oclif/config:twilio-cli using manifest from /Users/abadhwar/.twilio-cli/client/2.29.2/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /Users/abadhwar/.twilio-cli/package.json +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/package.json +1ms
  @oclif/config loading plugins [
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-help',
  '@oclif/plugin-plugins',
  '@oclif/plugin-warn-if-update-available',
  '@oclif/plugin-update'
] +1ms
  @oclif/config reading core plugin /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-autocomplete +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-autocomplete/package.json +3ms
  @oclif/config reading core plugin /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-help/package.json +0ms
  @oclif/config reading core plugin /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-plugins +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-plugins/package.json +0ms
  @oclif/config reading core plugin /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-warn-if-update-available +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-warn-if-update-available/package.json +0ms
  @oclif/config reading core plugin /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-update +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-update/package.json +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +1ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-plugins/oclif.manifest.json +1ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-update/oclif.manifest.json +0ms
  @oclif/config loadJSON /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-autocomplete using manifest from /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-update using manifest from /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-update/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-plugins using manifest from /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-warn-if-update-available using manifest from /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-warn-if-update-available/oclif.manifest.json +0ms
  @oclif/config config done +6ms
  @oclif/config start init hook +0ms
  twilio:twilio-cli:hooks:init start /Users/abadhwar/.twilio-cli/client/2.29.2/src/hooks/init/twilio-api +0ms
  twilio:twilio-cli:hooks:init start /Users/abadhwar/.twilio-cli/client/2.29.2/src/hooks/init/buy-phone-number +184ms
  twilio:twilio-cli:hooks:init start /Users/abadhwar/.twilio-cli/client/2.29.2/src/hooks/init/plugin-verification +2ms
  twilio:@oclif/plugin-update:hooks:init start /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-update/lib/hooks/init +0ms
  twilio:@oclif/plugin-warn-if-update-available:hooks:init start /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update +0ms
  twilio:twilio-cli:hooks:init done +47ms
  twilio:twilio-cli:hooks:init done +0ms
  twilio:twilio-cli:hooks:init done +0ms
  twilio:@oclif/plugin-update:hooks:init done +44ms
  twilio:@oclif/plugin-warn-if-update-available:hooks:init done +21ms
  @oclif/config init hook done +235ms
  twilio init version: @oclif/command@1.8.0 argv: [ 'update' ] +0ms
  @oclif/config runCommand update [] +3ms
  @oclif/config:@oclif/plugin-update require /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-update/lib/commands/update.js +239ms
  @oclif/config start prerun hook +18ms
  @oclif/config prerun hook done +0ms
  twilio:update init version: @oclif/command@1.8.0 argv: [] +0ms
  @oclif/config start preupdate hook +4ms
  @oclif/config preupdate hook done +0ms
  http → GET https://twilio-cli-prod.s3.amazonaws.com/channels/stable/twilio-darwin-x64-buildmanifest
  http   user-agent: 'twilio-cli/2.29.2 darwin-x64 node-v14.17.6' +0ms
  http ← GET https://twilio-cli-prod.s3.amazonaws.com/channels/stable/twilio-darwin-x64-buildmanifest 403
  http   connection: 'close'
  http   content-type: 'application/xml'
  http   date: 'Fri, 17 Sep 2021 12:37:22 GMT'
  http   server: 'AmazonS3'
  http   transfer-encoding: 'chunked'
  http   x-amz-id-2: 'BuXobS8NmC6WI/NxmD/aEKU4JMPvwsiFN9tkhwysfILBKbMcqEZg03TteWEy8/PWf0mq2t34YIA='
  http   x-amz-request-id: 'N7KE7QC6XBN08VAA'
  http '<?xml version="1.0" encoding="UTF-8"?>\n' +
  http   '<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>N7KE7QC6XBN08VAA</RequestId><HostId>BuXobS8NmC6WI/NxmD/aEKU4JMPvwsiFN9tkhwysfILBKbMcqEZg03TteWEy8/PWf0mq2t34YIA=</HostId></Error>' +1s
  twilio:update HTTP Error 403 for GET https://twilio-cli-prod.s3.amazonaws.com/channels/stable/twilio-darwin-x64-buildmanifest
  twilio:update <?xml version="1.0" encoding="UTF-8"?>
  twilio:update <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>N7KE7QC6XBN08VAA</RequestId><HostId>BuXobS8NmC6WI/NxmD/aEKU4JMPvwsiFN9tkhwysfILBKbMcqEZg03TteWEy8/PWf0mq2t34YIA=</HostId></Error> +1s
  http → GET https://twilio-cli-prod.s3.amazonaws.com/darwin-x64
  http   user-agent: 'twilio-cli/2.29.2 darwin-x64 node-v14.17.6' +3ms
  http ← GET https://twilio-cli-prod.s3.amazonaws.com/darwin-x64 200
  http   accept-ranges: 'bytes'
  http   cache-control: 'max-age=86400'
  http   connection: 'close'
  http   content-length: '331'
  http   content-type: 'application/json'
  http   date: 'Fri, 17 Sep 2021 12:37:25 GMT'
  http   etag: '"9f46ef47eb920cfde32c5ab378d0dbc3"'
  http   last-modified: 'Fri, 17 Sep 2021 11:27:14 GMT'
  http   server: 'AmazonS3'
  http   x-amz-id-2: 'KaI7xwb6+sVMuzqBJ9khQvkBtRE8LFPynyxeRETsKXL+kLVqOmTkPHpb99hfy2Lf6c9NPWV3faA='
  http   x-amz-request-id: '025BVS6DSDKEWPCC'
  http   x-amz-version-id: 'm34T2Rsl8F358DkdfEYZzMHrvF1HR0jY'
  http {
  http   version: '2.29.2',
  http   channel: 'stable',
  http   baseDir: 'twilio',
  http   gz: 'https://twilio-cli-prod.s3.amazonaws.com/twilio-v2.29.2/twilio-v2.29.2-darwin-x64.tar.gz',
  http   sha256gz: 'd512354bd6846b95d0b31025c64c96068ea3f18f3b9550274e2355f912d0ee28',
  http   node: { compatible: '>=10.12.0', recommended: '14.17.6' }
  http } +1s
twilio-cli: Updating CLI... done
  twilio:update tidy +1s
  twilio:update log chop +2ms
  @oclif/config start update hook +3s
  twilio:@oclif/plugin-plugins:hooks:update start /Users/abadhwar/.twilio-cli/client/2.29.2/node_modules/@oclif/plugin-plugins/lib/hooks/update.js +0ms
  @oclif/plugins Error: ENOENT: no such file or directory, open '/Users/abadhwar/.twilio-cli/package.json' +0ms
  twilio:@oclif/plugin-plugins:hooks:update done +2ms
  @oclif/config update hook done +2ms
  twilio:update done +11ms
  @oclif/config start postrun hook +1ms
  @oclif/config postrun hook done +0ms
7.00s user 5.02s system 45% cpu 26.587s total
∅ /usr/local/lib/twilio-cli/bin ❯                                                                                                                                                                             27s
```

**Comment by onuzbee** [comment] 2021-09-17 13:06
But later on, it still points to the original install location via the `.pkg` file: 

```
❯ which twilio
/usr/local/bin/twilio

```

**Comment by RodEsp** [comment] 2021-11-23 18:34
Hey @onuzbee, you're right that this shouldn't be failing silently so we'll definitely look into that. 

Looking at your debug log though it seems that the problem is that you're getting 403 from the http call that tries to fetch the manifest for the Twilio CLI.

You should make sure that `https://twilio-cli-prod.s3.amazonaws.com/channels/stable/twilio-darwin-x64-buildmanifest` is publicly available in your s3 bucket.
For example, for the `sfdx` CLI our manifest is publicly available at https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-darwin-x64-buildmanifest. 
If you copy-paste that URL into your browser it'll download the file to your computer, but if I copy paste your URL into my browser I get an access denied error.

![image](https://user-images.githubusercontent.com/1084688/143083496-f6337ef0-4070-499d-b037-45577f95cb3f.png)

**Comment by mdonnalley** [comment] 2024-02-05 21:36
Closing this since it appears to be an issue on Twilio's end

**Closed by mdonnalley** 2024-02-05 21:36 UTC
